name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Align Json Keys and Update Readme
        shell: pwsh
        run: |
          .\scripts\align-json-keys.ps1
          .\scripts\push-change.ps1 -message "chore: automatically align json keys"
          .\scripts\update-readme.ps1
          .\scripts\push-change.ps1

  git-mirror:
    name: Git Mirror
    needs: update
    runs-on: ubuntu-latest
    steps:
      - uses: abgox/git-mirror-action@main
        with:
          src_url: git@github.com:${{ github.repository }}.git
          dst_url: |
            - git@gitee.com:${{ github.repository }}.git
            - git@atomgit.com:${{ github.repository }}.git
          src_ssh_key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}
          dst_ssh_key: |
            - ${{ secrets.SSH_PRIVATE_KEY_GITEE }}
            - ${{ secrets.SSH_PRIVATE_KEY_ATOMGIT }}
