name: Update Content

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Align Json Keys and Update Readme
        shell: pwsh
        run: |
          .\scripts\align-json-keys.ps1
          .\scripts\push-change.ps1 -message "chore: automatically align json keys"
          .\scripts\update-readme.ps1
          .\scripts\push-change.ps1
